# -*- coding: utf-8 -*-
"""Codveda_task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cm9ShKRO-5JTJ_zmiC1TqzVVXWCcAZkZ
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = pd.read_csv('/content/drive/MyDrive/Codveda_tasks/task1/1) iris.csv')

data.head()

data.info()

print(data.isnull().sum())

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
data['species_encoded'] = le.fit_transform(data['species'])
data.head()

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
numerical_cols = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']
data[numerical_cols] = scaler.fit_transform(data[numerical_cols])
data.head()

from sklearn.model_selection import train_test_split

X = data.drop(['species', 'species_encoded'], axis=1)
y = data['species_encoded']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

data.to_csv('/content/drive/MyDrive/Codveda_tasks/task1/iris_modified.csv', index=False)

